### ISSUE TITLE
Shop Form

### ISSUE THREAD

**Issue by ttSpeaker** [dwfs-bue-pal-2/shelp#21]
#20 

- [x] Que el ingreso de la direccion del local tenga la funcionalidad predictiva de Google Maps
- [x] Que se verifique la validez de los datos en el form (largo, tipo de datos)
- [x]  Que no aparezca mas el score en el form
- [x] Que se pase la informacion de Lat y Long cuando se hace el submit del form

**Comment by folivarez** [comment]
para mi esta tareas son 5 horas

**Comment by ttSpeaker** [comment]
Esto se puede ir arrancando

**Comment by folivarez** [comment]
yo lo tomo si les parece
